# 网站基本信息
title: Home page
description: Home page
avatar:/img/fig-test.png
baseurl: 
url: "https://intproduct.github.io" 

# 使用远程主题
remote_theme: chrisrhymes/bulma-clean-theme

# 插件
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Markdown 处理器
markdown: kramdown
highlighter: rouge

# 分页设置（如果需要）
paginate: 5
paginate_path: "/blog/page:num/"

# 排除文件
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Bulma Clean Theme 特定配置
navbar_brand: Your Brand Name
navbar_color: is-primary

# Navigation
navigation:
  - name: Home
    link: /
  - name: Docs
    link: /docs/
  - name: Example Pages
    dropdown:
      - name: Page 1
        link: /example-pages/page1/
      - name: Page 2
        link: /example-pages/page2/
  - name: Blog
    link: /blog/

# 社交媒体链接（可选）
# github_username: yourusername
# twitter_username: yourusername
