# 基础配置（二选一）
## 方案A：使用 GitHub 官方主题（如 minimal）
theme: jekyll-theme-minimal

# 在 _config.yml 追加这些配置
plugins:
  - jekyll-feed  # 自动生成 RSS

# 数学公式支持（Kramdown 引擎）
kramdown:
  math_engine: katex

# 主题定制参数（以 Minimal Mistakes 为例）
minimal_mistakes:
  skin: "default"  # 可选 dark
  navigation:
    main:
      - title: "论文"
        url: /publications/
      - title: "仿真代码"
        url: /projects/
